### PR TITLE
Set API token in SlackNotificationConfig#getAsElement, fixes #86

### LINKED ISSUE #86: API Token on project level notification is lost after restart of TeamCity
API Token's configured on project level notifications are lost after TeamCity is restart.

Repro steps:
1. Create a project level notification with an API Token
2. Restart TeamCity
3. View previously created notification, the API token is lost

Looking in the generated settings XML you can see that the API token is not stored as part of the XML. I believe the problem is in the SlackNotificationConfig class in the core project. When  SlackNotificationConfig is instantiated with an Element it tries to read the "token" attribute, but the token attribute is never added in the getAsElement method.

### PR DESCRIPTION
**Pull request by tonybaroneee**
See #86

### CODE REVIEW

**Comment by pointerxr** [comment]
LGTM

Thanks

**Comment by pointerxr** [comment]
Can you please fix the tests? 

https://travis-ci.org/PeteGoo/tcSlackBuildNotifier/builds/153481798#L1439

**Comment by tonybaroneee** [comment]
Oh sure, sorry about that!

**Comment by tonybaroneee** [comment]
Sorry about that, see #122.

**Pull request merged**
