### PR TITLE
Allow notifications to only be raised on nominated branches

### PR DESCRIPTION
**Pull request by garethbragg**
We've had this hanging around for a while, and should really try to contribute back. May need some modernising to make it merge-able. Happy to take that on if you're keen.

This should add the ability to only notify Slack of build failures on nominated branches (e.g. alert the whole team if `master` breaks, but trust individuals/pairs to monitor their own branches).

Configurable through the UI exposed in teamcity:

image

### CODE REVIEW

**Comment by marvin-w** [comment]
Thanks, will probably have a look when I got some time - please note that the author of this project is no longer maintaining it.

**Comment by garethbragg** [comment]
Thanks @marvin-w, I wasn't aware of that. Certainly no rush to get this looked at.

I'm doing some work now to merge the latest `master` into our fork, which should resolve the conflicts we see here.

**Comment by garethbragg** [comment]
@marvin-w merge conflicts are now resolved :) Sorry it took so long.

**Comment by marvin-w** [comment]
thanks

**Comment by christophertrml** [comment]
@marvin-w With this feature merged, could you cut a release and publish it?

**Pull request merged**
